DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
MODEL:
    TYPE: cswin
    NAME: cswin_base_224
    DROPPATH: 0.5
    PATCH_SIZE: 4
    EMBED_DIM: 96
    DEPTHS: [2, 4, 32, 2]
    SPLIT_SIZES: [1, 2, 7, 7]
    NUM_HEADS: [4, 8, 16, 32]
TRAIN:
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 20
    BASE_LR: 1e-3
    WEIGHT_DECAY: 0.1
    MODEL_EMA: True
    MODEL_EMA_DECAY: 0.99992
