DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
MODEL:
    TYPE: cswin
    NAME: cswin_tiny_224
    DROPPATH: 0.2
    PATCH_SIZE: 4
    EMBED_DIM: 64
    DEPTHS: [1, 2, 21, 1]
    SPLIT_SIZES: [1, 2, 7, 7]
    NUM_HEADS: [2, 4, 8, 16]
TRAIN:
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 20
    BASE_LR: 2e-3
    WEIGHT_DECAY: 0.05
    MODEL_EMA: True
    MODEL_EMA_DECAY: 0.99984

