DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
MODEL:
    TYPE: T2T-ViT
    NAME: t2t-vit-7
    TRANS:
        EMBED_DIM: 256 
        DEPTH: 7
        NUM_HEADS: 4
        MLP_RATIO: 2.0
        QKV_BIAS: False
        QK_SCALE: None #256 ** -0.5
TRAIN:
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 3
    WEIGHT_DECAY: 0.3
    BASE_LR: 0.003
    WARMUP_START_LR: 1e-6
    END_LR: 5e-4
    ACCUM_ITER: 2


