DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
    BATCH_SIZE: 64
MODEL:
    TYPE: T2T-ViT
    NAME: t2t-vit-12
    EMBED_DIM: 256 
    DEPTH: 12
    NUM_HEADS: 4
    MLP_RATIO: 2.0
    QKV_BIAS: False
    QK_SCALE: None  # 256 ** -0.5
TRAIN:
    NUM_EPOCHS: 310
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.03
    BASE_LR: 1e-3
    WARMUP_START_LR: 1e-6
    END_LR: 1e-5
    ACCUM_ITER: 1


