DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: RepMLP
    NAME: repmlpres50_light_224_train
    MIXER:
        NUM_BLOCKS: [3,4,6,3]
        BLOCK_TYPE: 'light'
        DEPLOY: False
        

