DATA:
    IMAGE_SIZE: 224
    FMAP_SIZE: (14, 14)
    CROP_PCT: 0.875
MODEL:
    TYPE: BoTNet
    NAME: botnet50_224
    NUM_CLASSES: 1000
    PRETRAINED: None
    EMBED_DIM: 2048
    NUM_HEADS: 12
TRAIN:
    BASE_LR: 0.2
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 5.0e-05
