DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: hvt
    NAME: hvt_base_patch16_224
    PATCH_SIZE: 16
    EMBED_DIM: 384
    MLP_RATIO: 4.0
    DEPTH: 12
    NUM_HEADS: 6
    QKV_BIAS: True
    POOL_KERNEL_SIZE: 3
    POOL_STRIDE: 2
    POOL_BLOCK_WIDTH: 12
TRAIN:
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.025
    BASE_LR: 0.003
    WARMUP_START_LR: 1e-6
    END_LR: 5e-4
    ACCUM_ITER: 2


