DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
    GLOBAL_CROPS_SCALE: [0.25, 1.0]
    LOCAL_CROPS_SCALE: [0.05, 0.25]
    LOCAL_CROPS_NUMBER: 10
MODEL:
    TYPE: ViT
    NAME: vit_small_patch16_224
    OUT_DIM: 65536
    NORM_LAST_LAYER: False
    DROPPATH: 0.1
    TRANS:
        PATCH_SIZE: 16
        EMBED_DIM: 384
        MLP_RATIO: 4.0
        DEPTH: 12
        NUM_HEADS: 6
        QKV_BIAS: true
TRAIN:
    WARMUP_TEACHER_TEMP: 0.04
    TEACHER_TEMP: 0.07
    WARMUP_TEACHER_TEMP_EPOCHS: 30
    WEIGHT_DECAY: 0.04
    WEIGHT_DECAY_END: 0.4
    GRAD_CLIP: None
    NUM_EPOCHS: 800
    FREEZE_LAST_LAYER: 1
    BASE_LR: 0.0005
    WARMUP_EPOCHS: 10
    END_LR: 1e-5
    WARMUP_START_LR: 0.0
    ACCUM_ITER: 1
    MOMENTUM_TEACHER: 0.996
    USE_BN_IN_HEAD: False







    
