DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: cait
    NAME: cait_s36_384
    PATCH_SIZE: 16
    EMBED_DIM: 384
    DEPTH: 36
    NUM_HEADS: 8
    INIT_VALUES: 1e-6
    DEPTH_TOKEN_ONLY: 2
    DROPPATH: 0.2
