DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0

MODEL:
    TYPE: CvT
    NAME: CvT-w24-384
    NUM_CLASSES: 1000
    NUM_STAGES: 3
    PATCH_SIZE: [7, 3, 3]
    PATCH_STRIDE: [4, 2, 2]
    PATCH_PADDING: [2, 1, 1]
    DIM_EMBED: [192, 768, 1024]
    NUM_HEADS: [3, 12, 16]
    DEPTH: [2, 2, 20]
    ATTN_DROP_RATE: [0.0, 0.0, 0.0]
    DROP_RATE: [0.0, 0.0, 0.0]
    DROP_PATH_RATE: [0.0, 0.0, 0.3]
    CLS_TOKEN: [False, False, True]
