DATA:
    BATCH_SIZE: 32  # total bs=32, [per GPU is 4, 8 gpus]
    BATCH_SIZE_VAL: 1  # per GPU
    DATASET: 'ADE20K' # dataset name
    DATA_PATH: 'G:/TopFormer-main/data/ade/ADEChallengeData2016'
    CROP_SIZE: (448,448)  # input_size (training)
    NUM_CLASSES: 150
TRAIN:
    BASE_LR: 0.0003
    END_LR: 0.0
    ITERS: 160000
    IGNORE_INDEX: -1
    LOSS: "CrossEntropyLoss"
    LR_SCHEDULER:
        NAME: "WarmupPolyLR"
        WARM_UP_STEPS: 1500
        POWER: 1.0
    OPTIMIZER:
        NAME: 'ADAMW'
        WEIGHT_DECAY: 1e-2
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 448
    SIZE_DIVISOR: 32
    CROP_SIZE: [448, 448]
MODEL:
    NAME: "TopFomer"
    ENCODER:
        TYPE: 'TopTransformer'
    DECODER_TYPE: 'SimpleHead'
    SIMPLE:
        IS_DW: True
        IN_CHANNELS: [128, 128, 128]
        CHANNELS: 128
    DROP_PATH: 0.0
    DROPOUT: 0.0
    TRANS:
        MLP_RATIO: 2
        ATTEN_RATIO: 2.0
        NUM_HEADS: 4
        INPUT_CHANNELS: [16, 32, 64, 96]
        OUT_CHANNELS: [None, 128, 128, 128]
        EMBED_OUT_INDICE: [2, 4, 6, 8]
        DECODE_OUT_INDICES: [1, 2, 3]
        C2T_STRIDE: 2
        KEY_DIM: 16
        DEPTH: 4
        INJECTION: True
        INJECTION_TYPE: "multi_sum"
        CFGS: [[3,   1,  16, 1], # 1/2        0.464K  17.461M
               [3,   4,  16, 2], # 1/4 1      3.44K   64.878M
               [3,   3,  16, 1], #            4.44K   41.772M
               [5,   3,  32, 2], # 1/8 3      6.776K  29.146M
               [5,   3,  32, 1], #            13.16K  30.952M
               [3,   3,  64, 2], # 1/16 5     16.12K  18.369M
               [3,   3,  64, 1], #            41.68K  24.508M
               [5,   6,  96, 2], # 1/32 7     0.129M  36.385M
               [5,   6,  96, 1], #            0.335M  49.298M
             ]
    PRETRAINED: "C:/Users/Administrator/Downloads/PaddleViT-develop/topformer_tiny.pdparams"
SAVE_DIR: "./output/ade20k/topformer_tiny_448x448_160k_4x8_ade20k"
