DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: PVTv2
    NAME: pvtv2_tiny_224
    TRANS:
        PATCH_SIZE: 4
        EMBED_DIMS: [32, 64, 160, 256]
        STAGE_DEPTHS: [2, 2, 2, 2]
        NUM_HEADS: [1, 2, 5, 8]
        MLP_RATIO: [8, 8, 4, 4]
        SR_RATIO: [8, 4, 2, 1]
        QKV_BIAS: True

