DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: PVTv2
    NAME: pvtv2_b1
    PATCH_SIZE: 4
    EMBED_DIM: [64, 128, 320, 512]
    STAGE_DEPTH: [2, 2, 2, 2]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIO: [8, 8, 4, 4]
    SR_RATIO: [8, 4, 2, 1]
    QKV_BIAS: True
    DROPPATH: 0.1
TRAIN:
    GRAD_CLIP: None

