DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: PVTv2
    NAME: pvtv2_b5
    PATCH_SIZE: 4
    EMBED_DIM: [64, 128, 320, 512]
    STAGE_DEPTH: [3, 6, 40, 3]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIO: [4, 4, 4, 4]
    SR_RATIO: [8, 4, 2, 1]
    QKV_BIAS: True
    DROPPATH: 0.3
TRAIN:
    GRAD_CLIP: 1.0

