DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.96
MODEL:
    TYPE: convmixer
    NAME: convmixer_768_32
    CNN:
        DIM: 768
        DEPTH: 32
        KERNEL_SIZE: 7
        PATCH_SIZE: 7
        ACTIVATION: 'ReLU' 
TRAIN:
     BASE_LR: 0.01
     WARMUP_EPOCHS: 0
     CUTMIX_ALPHA: 0.5
     MIXUP_ALPHA: 0.5
     RANDOM_ERASE_PROB: 0.25
     GRAD_CLIP: 1.0
     OPTIMIZER:
         EPS: 1e-3
     AUTO_AUGMENT: True
