DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 1.0
MODEL:
    TYPE: xcit
    NAME: xcit_tiny_12_p16_224
    PATCH_SIZE: 16
    EMBED_DIM: 192
    DEPTH: 12
    NUM_HEADS: 4
    ETA: 1.0
    TOKENS_NORM: True
