DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: vit
    NAME: vit_base_patch32_384
    PATCH_SIZE: 32
    MLP_RATIO: 4.0
    QKV_BIAS: true
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    DROPOUT: 0.1  # same as paper
    ATTENTION_DROPOUT: 0.1  # same as paper
TRAIN:
    NUM_EPOCHS: 300  # same as paper
    WARMUP_EPOCHS: 32  # ~10k steps (4096 batch size)
    WEIGHT_DECAY: 0.3  # same as paper
    BASE_LR: 3e-3
    WARMUP_START_LR: 1e-6
    END_LR: 0.0
    GRAD_CLIP: 1.0
    ACCUM_ITER: 1
    OPTIMIZER:
        NAME: 'AdamW'
        BETAS: (0.9, 0.999)

VALIDATE_FREQ: 1
SAVE_FREQ: 10
REPORT_FREQ: 100

