DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: CrossViT
    NAME: crossvit_vit_tiny_224
    IMG_SIZE: [240, 224]
    PATCH_SIZE: [12, 16]
    EMBED_DIM: [96, 192]
    DEPTH: [[1, 4, 0], [1, 4, 0], [1, 4, 0]]
    NUM_HEADS: [3, 3]
    MLP_RATIO: [4, 4, 1]
    QKV_BIAS: True
    MULTI_CONV: False
