DATA:
    IMAGE_SIZE: 256
    CROP_PCT: 0.95
MODEL:
    TYPE: halo
    NAME: halonet_26t
    #PRETRAINED: halonet_26t_256
    ACT: relu
    BLOCK_SIZE: 8
    HALO_SIZE: 2
    STAGE1_BLOCK: ['bottle','bottle']
    STAGE2_BLOCK: ['bottle','bottle']
    STAGE3_BLOCK: ['bottle','attn']
    STAGE4_BLOCK: ['attn', 'attn']
    CHANNEL: [64,256,512,1024,2048]
    HIDDEN_CHANNEL: 1024
    NUM_HEAD: [0,0,8,8]
    STRIDE: [1,2,2,2]
    DEPTH: [2,2,2,2]
    NUM_CLASSES: 1000
TRAIN:
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 3
    WEIGHT_DECAY: 0.3
    BASE_LR: 0.003
    WARMUP_START_LR: 1e-6
    END_LR: 5e-4
    ACCUM_ITER: 1
